= CQ Bundle Plugin
:toc:
:toc-placement!:
:toc-title:

toc::[]


////
## Configuration ###

////


== Usage

`apply plugin: 'com.twcable.cq-bundle'`


[horizontal]
uploadBundle::
  Uploads the bundle to the CQ server. The task will fail if the bundle fails to start.

deleteBundle::
 Removes the current bundle from CQ. This task will not fail if the bundle does not exist.

startBundle::
  Start the bundle on the servers.

stopBundle::
  Stop the bundle on the servers.

refreshAllBundles::
  Tells CQ to refresh all the bundles. This gets added to the top-level project and generally a good idea
  to run after any of the other tasks.

showBundle::
  Shows a JSON representation of the information CQ has about the bundle, including its status,
    what bundles it is using, and what bundles are using it to STDOUT.


== Configuration

=== Convention: `slingServers`

By default, the plugin is initialized with the following effective configuration:

[source,groovy]
--
slingServers.with {
  retryWaitMs = 1000
  maxWaitValidateBundlesMs = 10000
  clusterAuths = false
  clusterPubs = false
  uninstallBundlesPredicate = { false }
  author.with {
    protocol = 'http'
    port = 4502
    machineName = 'localhost'
    username = 'admin'
    password = 'admin'
    installPath = '/apps/install'
    active = true
  }
  publisher.with {
    protocol = 'http'
    port = 4503
    machineName = 'localhost'
    username = 'admin'
    password = 'admin'
    installPath = '/apps/install'
    active = true
  }
}
--

To change the password for the author instance, for example, in the `build.gradle` file do

[source,groovy]
slingServers.author.password = "other_password"

The `active` property determines if it will try to interact with that server. If it has a problem connecting to
the server, it is automatically set to be `false` so it does not keep trying to attach to a server that is not running.

If `envJson` and `environment` properties are defined, the list of servers for this environment are extracted from
the JSON file.  See link:../src/main/groovy/com/twcable/gradle/sling/EnvironmentFileReader.groovy[EnvironmentFileReader]

=== Convention: `bundle`

By default, the plugin is initialized with the following effective configuration:

[source,groovy]
--
bundle.with {
  name = project.name
  symbolicName = // computed from project.group and project.name
  installPath = project.slingServers.author.installPath
  sourceFile = project.jar.archivePath
  slingServers = project.slingServers
}
--

`bundle` also has a `felixId` property that the plugin tries to determine dynamically from the server based on the
bundle's symbolic name.

== Task `createPackage`

This will create the `.zip` files that encapsulates a CQ Package file. It extends the `Zip` Gradle task, adding
special features to make it easier to work with for the specifics that CQ wants.

=== Features

Inclusion of bundles to install::
  By default any OSGi bundles that are depended upon by the project will be copied into the /apps/install folder to be
  https://sling.apache.org/documentation/bundles/jcr-installer-provider.html[automatically installed by Sling upon package installation].

Variable substitution of `META-INF/vault/definition/.content.xml` and `META-INF/vault/properties.xml`::
  The source files will be treated as templates with the Project properties passed in for substitution. Particularly
  useful for things like `${version}`.+++<br/>+++
  *NOTE:* There's currently a dependency for the `install` task between the project name (`project.name`) and the
  `"name"` values in these metadata files. See issue #24.

Explicit inclusion of bundles in `filter.xml`::
  Each of the bundles installed by the package receive their own `<filter/>` line in `filter.xml` to ensure that
  it gets cleanly removed upon package uninstallation without stepping on bundles that other packages may
  have installed. (Done via the `addBundlesToFilterXml` task, which uses the configuration of `createPackage`.)

=== Configuration

[horizontal]
bundleInstallRoot::
  Where to install included bundles in the JCR. **Defaults to `"/apps/install"`**

contentSrc::
  The filesystem location to act as the top-level of the content to put in the package.
  **Defaults to project.file("src/main/content")**

fileExclusions::
  Mutable list of common exclusions such as ++"**/.vlt", "**/.git/**"++, etc.
  Generally to modify this list you would mutate this in-place.

addAllBundles()::
  All the bundles that this depends on (project and non-project) will be copied into the _bundleInstallRoot_.
  **This is the default behavior.**

addProjectBundles()::
  Only the project-generated bundles that this depends on will be copied into
  the _bundleInstallRoot_.

addNonProjectBundles()::
  Only the non-project generated bundles that this depends on be will copied into
  the _bundleInstallRoot_.

addNoBundles()::
  None of the bundles that this depends on will be copied into the _bundleInstallRoot_.


==== Example usage

[source,groovy]
--
createPackage {
    addProjectBundles()
}
--

=== Dependency Configuration: `cq_package`

`cq_package` extends the `runtime` configuration, if it exists.

Example usage:

[source,groovy]
--
dependencies {
    compile project(':project-name')
    compile "net.tanesha:recaptcha4j:1.0.0"
}

configurations.cq_package {
    exclude group: 'javax.servlet', module: 'servlet-api'
}
--
